from bot.texts.donate.donate import (
    BTN_DONATE_CUSTOM,
    DONATE_CANCELLED,
    DONATE_CUSTOM_INVALID,
    DONATE_CUSTOM_PROMPT,
    DONATE_INVOICE_DESCRIPTION,
    DONATE_INVOICE_LABEL,
    DONATE_INVOICE_TITLE,
    DONATE_NOT_CONFIGURED,
    DONATE_SCREEN,
    DONATE_SUCCESS,
)

__all__ = [
    "BTN_DONATE_CUSTOM",
    "DONATE_CANCELLED",
    "DONATE_CUSTOM_INVALID",
    "DONATE_CUSTOM_PROMPT",
    "DONATE_INVOICE_DESCRIPTION",
    "DONATE_INVOICE_LABEL",
    "DONATE_INVOICE_TITLE",
    "DONATE_NOT_CONFIGURED",
    "DONATE_SCREEN",
    "DONATE_SUCCESS",
]
