from bot.constant.profile.profile import (
    CB_PLAYERS_PAGE_PREFIX,
    CB_PROFILE_DAILY_BONUS,
    CB_PROFILE_OPEN,
    CB_PROFILE_REFERRALS,
    CB_PROFILE_RENAME,
    CB_TOP_PREFIX,
    TOP_SCOPE_SEASON,
    TOP_SCOPE_TOTAL,
)

__all__ = [
    "CB_PLAYERS_PAGE_PREFIX",
    "CB_PROFILE_DAILY_BONUS",
    "CB_PROFILE_OPEN",
    "CB_PROFILE_REFERRALS",
    "CB_PROFILE_RENAME",
    "CB_TOP_PREFIX",
    "TOP_SCOPE_SEASON",
    "TOP_SCOPE_TOTAL",
]
