from bot.constant.profile.profile import (
    CB_PLAYERS_PAGE_PREFIX,
    CB_PROFILE_DAILY_BONUS,
    CB_PROFILE_REFERRALS,
    CB_PROFILE_RENAME,
)

__all__ = ["CB_PLAYERS_PAGE_PREFIX", "CB_PROFILE_DAILY_BONUS", "CB_PROFILE_REFERRALS", "CB_PROFILE_RENAME"]
