from bot.constant.referral.referral import (
    REFERRAL_DEEPLINK_PREFIX,
    TRANSACTION_REASON_REFERRAL_DONATE_CUT,
    TRANSACTION_REASON_REFERRAL_REWARD,
)

__all__ = [
    "REFERRAL_DEEPLINK_PREFIX",
    "TRANSACTION_REASON_REFERRAL_DONATE_CUT",
    "TRANSACTION_REASON_REFERRAL_REWARD",
]
